### PR TITLE
ABANDONED: Opts to attrs

### PR DESCRIPTION
**Pull request by nathwill**
still a lot of work to do before this is ready to merge, but the general idea is to add extra value where possible while maintaining attribute names. doing so through the modules, which will then be able to be used as mixins to help reduce duplication, since there's some overlap between certain resources' options, particularly for kill, resource-control, and exec unit options.

edit: longest... runon... ever.

### CODE REVIEW

**Comment by nathwill** [comment]
@ranjib @stevendanna well gents, this is kinda the next big set of changes that seems like it would be really helpful in moving towards a 1.0. 

As noted above the intention is to add value by using more type-appropriate resource attributes for any of the various systemd options whose values are "more than just a string" (e.g. booleans, or a one of a set of strings, integers, &c). For options that just take a string as an argument, it seems easier to just keep the option_attributes method around for setting those up.

in order to avoid doubly-defining the attributes in the resource definition, i'm partitioning the "enhanced" resource attributes into mixins so they can be automatically identified via `Module#instance_methods` and rejected from the option_attributes-generated attributes. that keeps it clean, but means we need to resort to the HWRP way of defining attributes via a method (for enhanced attributes only). seems a fair trade to me, but definitely open to suggestions if i'm missing an easier way to do this.

thoughts?

**Comment by ranjib** [comment]
@nathwill we can change the Options from array to a hash. key's being the directives and values representing valid types, then feed it in the resources directly,

i was also thinking what if we move the resources to library/resources, providers to library/providers and directives to library/directives, and get rid of the system_ from file names completely . it will be easier to navigate the code
finally it will be nice to have no Chef::Recipe.send(:include, Foo), its outright violation of OOPs :-(

**Comment by nathwill** [comment]
> we can change the Options from array to a hash. key's being the directives and values representing valid types, then feed it in the resources directly,

i really like this idea, and i'd even take it a step further: the values can be the entire options-hash argument for the attributes method call! booya!

>  what if we move the resources to library/resources, providers to library/providers and directives to library/directives, and get rid of the system_ from file names completely

sure, i can try, but my past experience with Chef is that any attempt at creating subdirectories beyond the top-level chef dirs is an exercise in frustration. we'll see how it goes this time.

> it will be nice to have no Chef::Recipe.send(:include, Foo)

hmmm, nothing related in this PR; I assume you're referring to [this](https://github.com/nathwill/chef-systemd/blob/master/libraries/helpers.rb#L120-L121)? i don't think we're actually using that anywhere, so i've got no objection to removing it via another PR. i've gone ahead and opened an [issue](https://github.com/nathwill/chef-systemd/issues/37) so we remember to remove it.

it was an idea for a helper method that seemed like it'd be useful for folks writing guards when supporting multiple service types (i know i write that guard all the time). As for it being a violation of OOPS, you'll have to spell that out in a bit more detail (with refs if possible), as I don't know what you're referring to (google-fu's not helpful here so far either :/), and this pattern is all over the place in the Chef community for injecting helper methods into the recipe context.

anyways, thanks (as always) for the great feedback! i'll start experimenting with the opts-as-hashes change and the library organization and see where we land.

**Comment by ranjib** [comment]
include is a private method for module inclusion offered by Module , while extend is public method offered by Object. Hence you cant do foo.include X (where foo is an instance of some class, and X being a module), while foo.extend X is perfectly valid. What it means is that, if a recipe wants to use the Systemd::Helper::Init module, it can use `extend Systemd:::Helpers::Init` . include inside recipe does not work, as the recipe code is instance evaled, extend will work . include on the other hand would have worked inside recipe if recipes' were class eval-ed.

**Comment by ranjib** [comment]
@nathwill  if you want, i'd be more than happy to do the library-sub directory separation. Top level libraries will only have the unit files, which will use require_relative for the directives. Most of the resource/provider has very little code, so we can keep them inside a single unit specific library file as well, keeping only the directives separate.

**Comment by nathwill** [comment]
@ranjib that'd be great. seems likely to generate some merge conflicts with the opt array->hash conversion, do you want to do that before or after?

**Comment by ranjib** [comment]
afterwards :0)

**Comment by nathwill** [comment]
:+1:

**Pull request closed without merging**
